version: '3'
services:
  mage:
    build:
      dockerfile: Dockerfile
    ports:
      - "17171:17171"
      - "17179:17179"
    extra_hosts:
      - "xmage.jshaw.dev:0.0.0.0"
    environment:
      - XMAGE_DOCKER_SERVER_ADDRESS=xmage.jshaw.dev
      - XMAGE_DOCKER_SERVER_NAME=xmage-server
      - XMAGE_DOCKER_MAX_SECONDS_IDLE=6000
      - XMAGE_DOCKER_AUTHENTICATION_ACTIVATED=false
    volumes:
      - xmage-db:/xmage/mage-server/db
volumes:
  xmage-db:
    driver: local
